@startuml

actor user
participant frontend
participant backend

user -> frontend: зайти на сайт, логин \n(открыть браузер)
frontend --> user: показать форму логина

user -> frontend: ввести email и пароль \nнажать "Войти"
frontend -> backend: POST /auth/login {email, password}

backend -> backend: найти пользователя в БД
backend -> backend: вычислить hash(password) и сравнить\nс hash из БД

backend --> frontend: 200 OK {accessToken / sessionId}
frontend --> user: показать личный кабинет \n(состояние "авторизован")

@enduml
